version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: 2gis-backend
    env_file: ./app/.env
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./site
      dockerfile: Dockerfile
    container_name: 2gis-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped